#ifndef GODESKTOP_GPU_SHADER_METAL_H
#define GODESKTOP_GPU_SHADER_METAL_H

static NSString *const shader = @
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"struct Instance { packed_float4 bounds, clip, color, uv; float radius; uint kind; packed_float2 padding; packed_float4 roundedBounds[4], roundedRadii; };\n"
"struct Out { float4 position [[position]]; float2 point, local, size, uv; float radius; float4 color; float4 clip; float4 rounded0 [[flat]], rounded1 [[flat]], rounded2 [[flat]], rounded3 [[flat]], roundedRadii [[flat]]; float2 shadowOrigin [[flat]]; float density [[flat]]; uint kind [[flat]], textureIndex [[flat]]; };\n"
"// Dispatch resource indices statically while retaining per-instance page selection.\n"
"float4 glyph_sample(const array<texture2d<float>,16> glyphs, uint index, float2 uv) {\n"
"  constexpr sampler s(filter::linear,address::clamp_to_edge);\n"
"  switch(index) {\n"
"    case 0: return glyphs[0].sample(s,uv,level(0));\n"
"    case 1: return glyphs[1].sample(s,uv,level(0));\n"
"    case 2: return glyphs[2].sample(s,uv,level(0));\n"
"    case 3: return glyphs[3].sample(s,uv,level(0));\n"
"    case 4: return glyphs[4].sample(s,uv,level(0));\n"
"    case 5: return glyphs[5].sample(s,uv,level(0));\n"
"    case 6: return glyphs[6].sample(s,uv,level(0));\n"
"    case 7: return glyphs[7].sample(s,uv,level(0));\n"
"    case 8: return glyphs[8].sample(s,uv,level(0));\n"
"    case 9: return glyphs[9].sample(s,uv,level(0));\n"
"    case 10: return glyphs[10].sample(s,uv,level(0));\n"
"    case 11: return glyphs[11].sample(s,uv,level(0));\n"
"    case 12: return glyphs[12].sample(s,uv,level(0));\n"
"    case 13: return glyphs[13].sample(s,uv,level(0));\n"
"    case 14: return glyphs[14].sample(s,uv,level(0));\n"
"    case 15: return glyphs[15].sample(s,uv,level(0));\n"
"    default: return float4(0);\n"
"  }\n"
"}\n"
"vertex Out vertex_main(uint vertexIndex [[vertex_id]], uint index [[instance_id]], const device Instance *instances [[buffer(0)]], constant float4 &frame [[buffer(1)]]) {\n"
"  float2 viewport=frame.xy;\n"
"  const float2 corners[6]={float2(0,0),float2(1,0),float2(0,1),float2(1,0),float2(1,1),float2(0,1)};\n"
"  Instance v=instances[index]; float2 corner=corners[vertexIndex]; Out o;\n"
"  o.point=float2(v.bounds.xy)+corner*float2(v.bounds.zw); o.size=v.bounds.zw; o.local=corner*o.size; o.radius=v.radius;\n"
"  if(v.kind==3) { float extent=max(0.001,length(float2(v.bounds.zw))); float2 axis=float2(v.bounds.zw)/extent;\n"
"    o.point=float2(v.bounds.xy)+corner.x*extent*axis+(corner.y-0.5)*v.radius*float2(-axis.y,axis.x);\n"
"    o.size=float2(extent,v.radius); o.local=corner*o.size; o.radius=0; }\n"
"  o.position=float4(o.point/viewport*float2(2,-2)+float2(-1,1),0,1);\n"
"  o.color=v.color; o.clip=v.clip; o.uv=float2(v.uv.xy)+corner*float2(v.uv.zw); o.kind=v.kind; o.textureIndex=uint(v.padding.x);\n"
"  o.shadowOrigin=float2(0); o.density=frame.z;\n"
"  if(v.kind==7) { o.local=o.point-float2(v.uv.xy); o.size=v.uv.zw; o.uv=float2(v.padding.y,0); o.shadowOrigin=v.uv.xy; }\n"
"  o.rounded0=v.roundedBounds[0]; o.rounded1=v.roundedBounds[1]; o.rounded2=v.roundedBounds[2]; o.rounded3=v.roundedBounds[3]; o.roundedRadii=v.roundedRadii; return o;\n"
"}\n"
"float rounded_coverage(float2 point,float4 bounds,float radius) { if(radius<=0) return 1.0; float2 q=abs(point-bounds.xy-bounds.zw*0.5)-(bounds.zw*0.5-radius); float distance=length(max(q,0.0))+min(max(q.x,q.y),0.0)-radius; float softness=max(fwidth(distance)*0.5,0.0001); return 1.0-smoothstep(-softness,softness,distance); }\n"
"// Gaussian rounded-mask convolution: exact strip and two bounded twelve-point caps.\n"
"float shadowCDF(float z) {\n"
"  float a=abs(z),t=1.0/(1.0+0.2316419*a);\n"
"  float polynomial=t*(0.319381530+t*(-0.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));\n"
"  float tail=0.3989422804014327*exp(-0.5*a*a)*polynomial; return z>=0?1.0-tail:tail;\n"
"}\n"
"float shadowInterval(float point,float lower,float upper,float sigma) { return max(0.0,shadowCDF((upper-point)/sigma)-shadowCDF((lower-point)/sigma)); }\n"
"#pragma clang fp reassociate(off) contract(off)\n"
"float shadowSumError(float a,float b,float sum) { float part=sum-a; return (a-(sum-part))+(b-part); }\n"
"float shadowProductError(float a,float b,float product) {\n"
"  float splitA=4097.0*a,splitB=4097.0*b,highA=splitA-(splitA-a),highB=splitB-(splitB-b);\n"
"  float lowA=a-highA,lowB=b-highB; return ((highA*highB-product)+highA*lowB+lowA*highB)+lowA*lowB;\n"
"}\n"
"float shadowCircleResidual(float x,float y,float radius) {\n"
"  float dx=radius-x,dy=radius-y,ex=shadowSumError(radius,-x,dx),ey=shadowSumError(radius,-y,dy);\n"
"  float rr=radius*radius,xx=dx*dx,yy=dy*dy,first=rr-xx,second=first-yy;\n"
"  float tail=shadowProductError(radius,radius,rr)-shadowProductError(dx,dx,xx)-shadowProductError(dy,dy,yy);\n"
"  tail=tail-2*dx*ex-2*dy*ey-ex*ex-ey*ey;\n"
"  tail=tail+shadowSumError(rr,-xx,first)+shadowSumError(first,-yy,second); return second+tail;\n"
"}\n"
"float shadowCap(float2 point,float2 size,float radius,float sigma,float lower,float upper,bool top) {\n"
"  lower=max((lower-point.y)/sigma,-4.0); upper=min((upper-point.y)/sigma,4.0); if(upper<=lower) return 0.0;\n"
"  const float nodes[12]={-0.981560634,-0.904117256,-0.769902674,-0.587317954,-0.367831499,-0.125233409,0.125233409,0.367831499,0.587317954,0.769902674,0.904117256,0.981560634};\n"
"  const float weights[12]={0.0471753364,0.106939326,0.160078329,0.203167427,0.233492537,0.249147046,0.249147046,0.233492537,0.203167427,0.160078329,0.106939326,0.0471753364};\n"
"  float middle=(lower+upper)*0.5,interval=(upper-lower)*0.5,total=0.0;\n"
"  float edge=top?point.y:size.y-point.y,residual=shadowCircleResidual(point.x,edge,radius);\n"
"  for(uint i=0;i<12;i++) { float normalized=middle+interval*nodes[i],delta=(top?1.0:-1.0)*sigma*normalized;\n"
"    float root=sqrt(max(0.0,edge*(2*radius-edge)+delta*(2*(radius-edge)-delta))),denominator=root+(radius-point.x);\n"
"    float circle=(delta*(2*(radius-edge))+residual)-delta*delta;\n"
"    float left=point.x<radius && denominator>0.0?circle/denominator:point.x-radius+root,right=size.x-point.x-radius+root;\n"
"    float horizontal=max(0.0,shadowCDF(right/sigma)-shadowCDF(-left/sigma)); total+=weights[i]*horizontal*exp(-0.5*normalized*normalized); }\n"
"  return total*interval*0.3989422804014327;\n"
"}\n"
"#pragma clang fp reassociate(on) contract(fast)\n"
"float shadowBoxInterval(float samplePoint,float lower,float upper,float pixelWidth) { return max(0.0,min(upper,samplePoint+pixelWidth*0.5)-max(lower,samplePoint-pixelWidth*0.5))/pixelWidth; }\n"
"float shadowBoxCap(float2 samplePoint,float2 size,float radius,float2 pixelSize,float lower,float upper,bool top) {\n"
"  lower=max(lower,samplePoint.y-pixelSize.y*0.5); upper=min(upper,samplePoint.y+pixelSize.y*0.5); if(upper<=lower) return 0.0;\n"
"  const float nodes[8]={-0.960289856,-0.796666477,-0.525532410,-0.183434642,0.183434642,0.525532410,0.796666477,0.960289856};\n"
"  const float weights[8]={0.101228536,0.222381034,0.313706646,0.362683783,0.362683783,0.313706646,0.222381034,0.101228536};\n"
"  float middle=(lower+upper)*0.5,interval=(upper-lower)*0.5,total=0.0;\n"
"  for(uint i=0;i<8;i++) { float y=middle+interval*nodes[i],edge=top?y:size.y-y;\n"
"    float inset=radius-sqrt(max(0.0,edge*(2*radius-edge))); total+=weights[i]*shadowBoxInterval(samplePoint.x,inset,size.x-inset,pixelSize.x); }\n"
"  return total*interval/pixelSize.y;\n"
"}\n"
"float shadowCoverage(float2 local,float2 size,float radius,float sigma) {\n"
"  float2 point=local; radius=clamp(radius,0.0,min(size.x,size.y)*0.5);\n"
"  if(sigma<=0.0) { float2 pixelSize=max(fwidth(local),float2(0.0001));\n"
"    float sharp=shadowBoxInterval(point.x,0.0,size.x,pixelSize.x)*shadowBoxInterval(point.y,radius,size.y-radius,pixelSize.y);\n"
"    if(radius>0.0) { sharp+=shadowBoxCap(point,size,radius,pixelSize,0.0,radius,true); sharp+=shadowBoxCap(point,size,radius,pixelSize,size.y-radius,size.y,false); }\n"
"    return clamp(sharp,0.0,1.0); }\n"
"  // Reflect the symmetric mask toward top/left to preserve tiny cap offsets.\n"
"  point=float2(min(local.x,size.x-local.x),min(local.y,size.y-local.y));\n"
"  float coverage=shadowInterval(point.x,0.0,size.x,sigma)*shadowInterval(point.y,radius,size.y-radius,sigma);\n"
"  if(radius>0.0) { coverage+=shadowCap(point,size,radius,sigma,0.0,radius,true); coverage+=shadowCap(point,size,radius,sigma,size.y-radius,size.y,false); }\n"
"  return clamp(coverage,0.0,1.0);\n"
"}\n"
"fragment float4 fragment_main(Out in [[stage_in]], const array<texture2d<float>,16> glyphs [[texture(0)]], texture2d<float> bitmap [[texture(16)]]) {\n"
"  if(any(in.point<in.clip.xy)||any(in.point>=in.clip.xy+in.clip.zw)) discard_fragment();\n"
"  float coverage=rounded_coverage(in.point,in.rounded0,in.roundedRadii.x)*rounded_coverage(in.point,in.rounded1,in.roundedRadii.y)*rounded_coverage(in.point,in.rounded2,in.roundedRadii.z)*rounded_coverage(in.point,in.rounded3,in.roundedRadii.w); if(coverage<=0) discard_fragment();\n"
"  if(in.kind==7) {\n"
"#pragma clang fp reassociate(off) contract(off)\n"
"    float2 local=in.local;\n"
"    if(in.uv.x>0) {\n"
"#pragma clang diagnostic push\n"
"#pragma clang diagnostic error \"-Wunknown-pragmas\"\n"
"#pragma METAL fp math_mode(safe)\n"
"#pragma METAL fp contract(off)\n"
"      local=precise::divide(in.position.xy,float2(in.density))-in.shadowOrigin;\n"
"#pragma clang diagnostic pop\n"
"    }\n"
"    float alpha=shadowCoverage(local,in.size,in.radius,in.uv.x)*in.color.a; return float4(in.color.rgb*alpha,alpha)*coverage;\n"
"  }\n"
"  if(in.kind==5) { constexpr sampler s(filter::linear,address::clamp_to_edge); float4 rgba=bitmap.sample(s,in.uv); return float4(rgba.rgb*in.color.rgb*in.color.a,rgba.a*in.color.a)*coverage; }\n"
"  if(in.kind==6) { return glyph_sample(glyphs,in.textureIndex,in.uv)*in.color.a*coverage; }\n"
"  if(in.kind==2) { float alpha=glyph_sample(glyphs,in.textureIndex,in.uv).r*in.color.a; return float4(in.color.rgb*alpha,alpha)*coverage; }\n"
"  float2 q=abs(in.local-in.size*0.5)-(in.size*0.5-in.radius); float distance=length(max(q,0.0))+min(max(q.x,q.y),0.0)-in.radius;\n"
"  float softness=max(fwidth(distance)*0.5,0.0001); float alpha=(1.0-smoothstep(-softness,softness,distance))*in.color.a; return float4(in.color.rgb*alpha,alpha)*coverage;\n"
"}\n";
#endif
