// shadergen produces checked-in DXIL. Application builds need no shader compiler
// DLL, downloaded executable, Rust dependency, or network access.
package main

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	dxc := flag.String("dxc", "dxc", "path to DXC 1.9.2609.5")
	check := flag.Bool("check", false, "verify generated bytes without modifying the checked-in header")
	flag.Parse()
	compiler, err := exec.LookPath(*dxc)
	if err != nil {
		return err
	}
	compiler, err = filepath.Abs(compiler)
	if err != nil {
		return err
	}
	version, err := exec.Command(compiler, "--version").CombinedOutput()
	if err != nil {
		return fmt.Errorf("DXC version: %w: %s", err, version)
	}
	if !bytes.Contains(version, []byte("1.9.2609.5")) {
		return fmt.Errorf("expected DXC 1.9.2609.5; got %s", version)
	}
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	sourceRoot := filepath.Join(root, "internal", "platform", "shaders")
	source, err := os.ReadFile(filepath.Join(sourceRoot, "ui.hlsl"))
	if err != nil {
		return err
	}
	abi, err := os.ReadFile(filepath.Join(root, "internal", "platform", "gpu_scene.h"))
	if err != nil {
		return err
	}
	// The hash uses normalized newlines so checkout.autocrlf does not change it.
	normalize := func(b []byte) []byte { return bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n")) }
	combined := append(append(normalize(source), '\x00'), normalize(abi)...)
	digest := sha256.Sum256(combined)
	dir, err := os.MkdirTemp("", "godesktop-dxil-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(dir)
	var generated bytes.Buffer
	fmt.Fprintf(&generated, "// Generated by internal/shadergen using DXC 1.9.2609.5; DO NOT EDIT.\n// Source + GPU ABI SHA256: %x\n", digest)
	for _, shader := range []struct{ name, entry, profile string }{{"gd_dx12_vertex", "vertex_main", "vs_6_0"}, {"gd_dx12_fragment", "fragment_main", "ps_6_0"}} {
		output := filepath.Join(dir, shader.name+".dxil")
		command := exec.Command(compiler, "-T", shader.profile, "-E", shader.entry, "-O3", "-WX", "-Qstrip_debug", "-Qstrip_reflect", "-Fo", output, "ui.hlsl")
		command.Dir = sourceRoot
		if result, err := command.CombinedOutput(); err != nil {
			return fmt.Errorf("%s: %w: %s", shader.entry, err, result)
		}
		data, err := os.ReadFile(output)
		if err != nil {
			return err
		}
		if len(data) < 32 || !bytes.Equal(data[:4], []byte("DXBC")) || !bytes.Contains(data, []byte("DXIL")) {
			return errors.New("DXC did not produce a DXIL container")
		}
		fmt.Fprintf(&generated, "// %s, %s, %d bytes\nstatic const unsigned char %s[] = {", shader.entry, shader.profile, len(data), shader.name)
		for i, value := range data {
			if i%16 == 0 {
				generated.WriteString("\n    ")
			}
			fmt.Fprintf(&generated, "0x%02x,", value)
		}
		generated.WriteString("\n};\n")
	}
	target := filepath.Join(root, "internal", "platform", "gpu_shader_dx12.inc")
	if *check {
		existing, err := os.ReadFile(target)
		if err != nil {
			return err
		}
		if !bytes.Equal(normalize(existing), generated.Bytes()) {
			return errors.New("DXIL is stale or was generated with a different compiler; regenerate and review it")
		}
		fmt.Println("DXIL matches HLSL, GPU instance ABI and pinned DXC")
		return nil
	}
	if err = os.WriteFile(target, generated.Bytes(), 0644); err != nil {
		return err
	}
	fmt.Println("Generated", target)
	return nil
}
